#image_encoder:
_target_: modeling.backbone.hiera.HieraEncoder
scalp: 0
trunk:
  _target_: external.sam2.modeling.backbones.hieradet.Hiera
  embed_dim: 96
  num_heads: 1
  stages: [1, 2, 11, 2]
  global_att_blocks: [7, 10, 13]
  window_pos_embed_bkg_spatial_size: [7, 7]
neck:
  _target_: external.sam2.modeling.backbones.image_encoder.FpnNeck
  position_encoding:
    _target_: external.sam2.modeling.position_encoding.PositionEmbeddingSine
    num_pos_feats: 256
    normalize: true
    temperature: 10000
  d_model: 256
  backbone_channel_list: [768, 384, 192, 96]
  fpn_top_down_levels: [2, 3]
  fpn_interp_model: nearest
ckpt_path: null #PretrainedModels/sam2_hiera_small.pt