#image_encoder:
_target_: modeling.backbone.hiera.HieraEncoder
scalp: 0
trunk:
  _target_: external.sam2.modeling.backbones.hieradet.Hiera
  embed_dim: 112
  num_heads: 2
neck:
  _target_: external.sam2.modeling.backbones.image_encoder.FpnNeck
  position_encoding:
    _target_: external.sam2.modeling.position_encoding.PositionEmbeddingSine
    num_pos_feats: 256
    normalize: true
    scale: null
    temperature: 10000
  d_model: 256
  backbone_channel_list: [896, 448, 224, 112]
  fpn_top_down_levels: [2, 3]  # output level 0 and 1 directly use the backbone features
  fpn_interp_model: nearest
ckpt_path: PretrainedModels/sam2_hiera_base_plus.pt